FROM apache/hive:4.0.0

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && curl -fSL "https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.3/postgresql-42.7.3.jar" \
        -o /opt/hive/lib/postgresql-jdbc.jar \
    && apt-get remove -y curl \
    && rm -rf /var/lib/apt/lists/*

USER hive
