global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["api:8000"]
    metrics_path: "/metrics"

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9101"]

  - job_name: "spark-master"
    static_configs:
      - targets: ["spark-master:8080"]
    metrics_path: "/metrics/json"
    scrape_interval: 30s

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
